### ISSUE TITLE
Issue on VisClustering() with too many cells

### ISSUE THREAD

**Issue by wfujibuchilab** [elolab/Totem#1]
Hi. When I try to plot cells in MDS space using VisClustering() with too many cells (≥30,000), the plotting resolution decreases, resulting in poor-quality graphics. What is causing this issue, and is there a way to fix it? Attached please see the odd graphics.
![image](https://github.com/user-attachments/assets/5f71660d-22b0-4ca7-a0d6-8bc67cc8be2d)

**Comment by antonioggsousa** [comment]
Hi, 

`Totem` relies on third-party software to plot the data. In this case, it relies on [dynplot::plot_dimred()](https://dynverse.org/reference/dynplot/plot_trajectory/plot_dimred/) to visualize a user-provided clustering. 

At first look, it seems to me that `dynplot::plot_dimred()` uses `geom_polygon()` instead of `geom_point()` for larger data sets, as it is your case. I'm not certain of this as I didn't have time to check the source code. 

In any case, you can achieve your aim by replacing the `geom_polygon()` layer by a newly computed `geom_point()` layer using `ggplot2` syntax (and a bit of "hacking"). 

```
## Packages
library("ggplot2")
library("Totem")

# Get your plot
p <- VizClustering(sce, clustering = as.character(sce$cell_type), viz.dim.red = dim_red)

# Copy the plot above
plt <- p

# Create a 'geom_point' layer in the ggplot 'plt'
geom.point <- plt + geom_point(mapping = aes(x = comp_1, y = comp_2), color = plt$data$color) 

# Replace the 'geom_polygon' layer by the new 'geom_point' layer created above
plt$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]

# Plot 
plt
```

Please let us know below if this answered your question(s) in order to close the issue. 

Thank you for your interest in `Totem`!

Best, 

António

**Comment by wfujibuchilab** [comment]
Thank you for your quick solution. However, there is an another issue. When I changed the cluster-labeling style as you suggested in the previous email, it complains and did not show anything.
```r
cluster.names <- unique(p$data$milestone_id)
color.names <- unique(p$data$color)
# If you want a legend but keeping the same colors
names(color.names) <- color.names
names(cluster.names) <- color.names
#cluster.names <- sort(cluster.names)
cluster.names <- cluster.names[order(nchar(cluster.names), cluster.names)]
pp <- p + scale_color_manual(name = "", values = color.names, labels = cluster.names, breaks = names(cluster.names)) + theme(legend.text = element_text(size=14, hjust=0.5), legend.title.position = "top") + guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))

plt <- pp
geom.point <- plt + geom_point(mapping = aes(x = comp_1, y = comp_2), color = plt$data$color)
plt$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
pp$layers[3:7] <- NULL
print(plt)
```
I hope that you could kindly tell me a way to solve both requests at the same time. Thank you.

-W

**Comment by antonioggsousa** [comment]
Hi, 

Please try the following code snippet and let us know if this works for you: 

```
# Print the plot to see how it looks
p 
plt <- p # copy the plot

# Create 'geom_point' layer to replace 'geom_polygon'
geom.point <- plt + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
plt$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]] # replace "geom_polygon" by "geom_point"
plt # print to see how the plot looks like

# Create a new plot to add legend
cluster.names <- unique(p$data$milestone_id)
color.names <- unique(p$data$color)
# If you want a legend but keeping the same colors
names(color.names) <- color.names
names(cluster.names) <- color.names
cluster.names <- cluster.names[order(nchar(cluster.names), cluster.names)]
plt2 <- plt + scale_color_manual(name = "", values = color.names, labels = cluster.names, breaks = names(cluster.names)) +
  theme(legend.text = element_text(size=14, hjust=0.5), legend.title.position = "top") + 
  guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))
plt2 

# Remove tree and labels in the plot
plt3 <- plt2 # copy another the plot
plt3$layers[3:7] <- NULL
plt3 # print the plot
```

This worked for a dummy example, but we can't promise will work for you as you're using a different R environment and objects. 

Please be careful doing all these modifications as errors can be introduced easily. 

Hopefully this fixes all the issues. 
Let us know below.

Best, 
António

**Comment by wfujibuchilab** [comment]
Dear António,

Thank you again for your quick response. The plt2 seemed to work but the plt3 did not.

plt3:
<img width="425" alt="スクリーンショット 2024-09-25 10 23 29" src="https://github.com/user-attachments/assets/7bbb4745-0a37-4447-886e-4ac4abb423ea">

FYI, this is the second layer of plt2:
```r
> plt2[[2]]
[[1]]
mapping: x = ~comp_1, y = ~comp_2, colour = ~color 
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 

[[2]]
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 

[[3]]
mapping: x = ~.data$comp_1, y = ~.data$comp_2, group = ~.data$group 
geom_path: lineend = butt, linejoin = round, linemitre = 10, arrow = NULL, na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 

[[4]]
mapping: x = ~.data$comp_1, y = ~.data$comp_2, group = ~.data$group 
geom_path_interpolate: arrow = NULL, lineend = butt, na.rm = FALSE
stat_link2: na.rm = FALSE, n = 100
position_identity 

[[5]]
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 

[[6]]
mapping: label = ~.data$label 
geom_label: parse = FALSE, label.padding = 0.25, label.r = 0.15, label.size = 0.25, size.unit = mm, na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity
```
I guess that we need to replace "plt3$layers[3:7] <- NULL” with "plt3$layers[2:6] <- NULL” ?
Hope it is helpful to fix it. Again, thank you for your kind support.

Best regards,
-W

**Comment by antonioggsousa** [comment]
Dear Wataru, 

It depends. Do you also want to exclude the centroid points that appear in your `plt2` plot above? If so, you're right,  `plt3$layers[3:7] <- NULL` needs to be replaced by `plt3$layers[2:6] <- NULL`. Otherwise `plt3$layers[3:6] <- NULL` is enough. 

Our understanding is that all issues were addressed and, thus, we're closing this GitHub issue. 

If there is anything else, you can re-open the issue or open a new issue. 

Thank you for your interest in `Totem` and we hope you continue to enjoy it. 
Best regards, 
António

**Comment by wfujibuchilab** [comment]
Dear António,

Thank you for your reply. I solved the VisClustering() issue, but this geom_polygon() problem persists to other functions such as VizCellConnectivity() and VizSmoothedTraj().
<img width="567" alt="スクリーンショット 2024-09-25 18 29 20" src="https://github.com/user-attachments/assets/b5b266fb-4e77-4ce3-854b-a882be4e6a48">
Is there any way to solve all the problems easily, as it is embarrassing?
For example, can you replace geom_polygon() function with geom_points() directly?

Best regards,
-WF

**Comment by antonioggsousa** [comment]
Dear Wataru, 

No, we can't just simply replace `geom_polygon()` by `geom_point()`, because as I mentioned above `Totem` relies on third-party software tools for visualization, specifically the [dynplot](https://github.com/dynverse/dynplot) package. 

These issues can be easily addressed with a custom function. 

Below I provide a function to address most, if not all, the issues addressed in this post: 

```
plot_totem <- function(SCE, plot.function, params = list(), plot.labels = TRUE, 
                       plot.polygons = TRUE, plot.trajectory = TRUE, 
                       plot.centroids = TRUE, plot.legend = FALSE) {
  # Packages required
  require("ggplot2")
  require("Totem")
  require("dynplot")
  
  # Plot 
  run.fun <- TRUE
  if (all(isTRUE(all.equal(get(substitute(plot.function)), Totem::VizSmoothedTraj)) & (plot.polygons == FALSE))) run.fun <- FALSE
  if (run.fun) p <- do.call(plot.function, c(object = SCE, params))
  
  if (!plot.polygons) { # if 'plot.polygons' is FALSE, replace 'geom_polygon' by 'geom_point'
    if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizClustering))) {
      if (plot.legend) {
        geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
        p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
      } else {
        geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2), color = p$data$color)
        p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
      }
    } else if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizCellConnectivity))) {
      geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
      p$layers[[1]] <- geom.point$layers[[2]]
      p <- p + 
        scale_color_distiller("cell_connectivity expression", palette = "RdYlBu")
    } else {
      vizsmoothedtraj.custom <- function (object, traj.names = NULL, 
                                          dim.red.type = NULL, 
                                          viz.dim.red = NULL, 
                                          plot.pseudotime = FALSE) {
        require("SingleCellExperiment")
        if (identical(reducedDimNames(object), character(0))) {
          message("No dimensionality reduced data available. ", 
                  "Using data in the 'logcounts' slot.")
          X <- logcounts(object)
          X <- as.matrix(Matrix::t(X))
        }
        else {
          X <- reducedDim(object)
        }
        if (!is.null(dim.red.type)) {
          X <- reducedDim(object, type = dim.red.type)
        }
        plot_list <- list()
        model <- metadata(object)$totem$dynwrap_trajectory[[traj.names]]
        if (plot.pseudotime) {
          plot_list[[traj.names]] <- dynplot::plot_dimred(model, color_cells = "pseudotime",
                                                          dimred = viz.dim.red) + ggtitle(traj.names)
        }
        else {
          plot_list[[traj.names]] <- dynplot::plot_dimred(model, label_milestones = TRUE, 
                                                          dimred = viz.dim.red) + ggtitle(traj.names)
        }
        return(plot_list[[traj.names]])
      }
      p <- vizsmoothedtraj.custom(object = SCE, traj.names = params$traj.names,
                                  dim.red.type = params$dim.red.type, 
                                  viz.dim.red = params$viz.dim.red, 
                                  plot.pseudotime = ifelse(is.null(params$plot.pseudotime), FALSE, params$plot.pseudotime))
      geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
      p$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
      p <- p + ggplot2::scale_color_viridis_c("pseudotime")
    }
  }
  
  # Remove layers
  eval.exp <- c(!plot.centroids, !plot.trajectory, !plot.labels)
  if (any(eval.exp)) {
    rm.layers <- c()
    if (!plot.centroids) rm.layers <- append(rm.layers, 2)
    if (!plot.trajectory) rm.layers <- append(rm.layers, 3:5)
    if (!plot.labels) rm.layers <- append(rm.layers, 6) 
    p$layers[rm.layers] <- NULL
  }
  
  # Add legend
  if (plot.legend) {
    # Keep the same colors
    cluster.names <- unique(p$data$milestone_id)
    color.names <- unique(p$data$color)
    # If you want a legend but keeping the same colors
    names(color.names) <- color.names
    names(cluster.names) <- color.names
    cluster.names <- cluster.names[order(nchar(cluster.names), cluster.names)]
    # Plot
    p <- p + scale_color_manual(name = "", values = color.names, labels = cluster.names, breaks = names(cluster.names)) +
      theme(legend.text = element_text(size=14, hjust=0.5), legend.title.position = "top") + 
      guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))
  }
  return(p)
}
``` 

You can run/source the `plot_totem()` function above and, then, run the code below (adapting to your variable names) to compare the original functions to the customized `plot_totem()` function, which takes as input the three functions you mentioned - `VizCellConnectivity()`, `VizClustering()`, `VizSmoothedTraj()`.

```
# Original plots
orig.vizconn.plt <- VizCellConnectivity(object = sce, viz.dim.red = dim_red) # VizCellConnectivity
orig.vizclt.plt <- VizClustering(sce, clustering = as.character(sce$cell_type), viz.dim.red = dim_red) # VizClustering
orig.vizsmoth.plt <- VizSmoothedTraj(object = sce, traj.names = select.cluster, # VizSmoothedTraj
                                     viz.dim.red = dim_red, plot.pseudotime = TRUE) 

# New customized plots
new.vizconn.plt <- plot_totem(SCE = sce, plot.function = VizCellConnectivity, # VizCellConnectivity
                              params = list(viz.dim.red = dim_red), plot.polygons = FALSE)
new.vizclt.pl <- plot_totem(SCE = sce, plot.function = VizClustering, # VizClustering
                            params = list(clustering = as.character(sce$cell_type), viz.dim.red = dim_red), 
                            plot.polygons = FALSE, plot.labels = FALSE, plot.trajectory = FALSE, 
                            plot.centroids = FALSE, plot.legend = TRUE)
new.vizsmoth.plt <- plot_totem(SCE = sce, plot.function = VizSmoothedTraj, # VizSmoothedTraj
                               params = list(traj.names = select.cluster, viz.dim.red = dim_red, plot.pseudotime = TRUE), 
                               plot.polygons = FALSE)

# Plot altogether 
cowplot::plot_grid(orig.vizconn.plt, orig.vizclt.plt, orig.vizsmoth.plt, # original plots
                   new.vizconn.plt, new.vizclt.pl, new.vizsmoth.plt, # new.vizsmoth.plt,
                   ncol = 3, align = "vh", labels = c("Original", "", "", "plot_totem()", "", ""))
```

The result for a dummy dataset can be seen below: 

![plot_totem](https://github.com/user-attachments/assets/1503211f-ce07-4319-aa33-d07583ddafef)


Hopefully, the `plot_totem()` function addresses all the issues you've mentioned. 

Best regards, 
António

**Comment by wfujibuchilab** [comment]
Thank you, António, for kindly providing a new function of plot_totem()!

Actually, we are using more drawing functions such as VizMST() and VizFeatureExpression(), which have the same geom_polygon() problem, in our analysis. Could you kindly add all the visualization functions to your plot_totem() function so that users do not get embarrassed with many cells?

Single-cell analysis with a large number of cells is becoming a standard so I believe that it would be very useful to provide plot_totem() in the next version of Totem.

Thank you so much.

Best regards,
-WF

**Comment by wfujibuchilab** [comment]
Hi,

When I tried to run plot_totem(), there is an error message came out.
```r
> plots <- plot_totem(SCE = sce, plot.function = VizSmoothedTraj, params = list(traj.names = ReturnTrajNames(sce), viz.dim.red = dim_red, plot.pseudotime = FALSE), plot.polygons = FALSE)
Error in metadata(object)$totem$dynwrap_trajectory[[traj.names]] : 
  no such index at level 2
```
I do not know what happens here so I hope you could fix it.

Also the original plot_tetem() exampl code for VizClustering() did not work.
```r
> new.vizclt.pl <- plot_totem(SCE = sce, plot.function = VizClustering, params = list(clustering = as.character(sce$cell_type), viz.dim.red = dim_red), plot.polygons = FALSE, plot.labels = FALSE, plot.trajectory = FALSE, plot.centroids = FALSE, plot.legend = TRUE)
Error in split.default(seq_len(nrow(X)), clustering) : 
  group length is 0 but data length > 0
```
When you changed “sce$cell_type” to “sce$ident”, it worked well.
```r
> new.vizclt.pl <- plot_totem(SCE = sce, plot.function = VizClustering, params = list(clustering = as.character(sce$ident), viz.dim.red = dim_red), plot.polygons = FALSE, plot.labels = FALSE, plot.trajectory = FALSE, plot.centroids = FALSE, plot.legend = TRUE)
Coloring by milestone
Using milestone_percentages from trajectory
```
Thank you.
-WF

**Comment by antonioggsousa** [comment]
Dear Wataru, 

Indeed, single-cell data is growing in size and it would be beneficial to have the option to plot all cells for larger datasets in a new release. We'll discuss this internal and consider to add it in the next release. Thank you for the suggestion. 

I added below the function `plot_totem()`, now with support to the functions `VizMST()` and `VizFeatureExpression()`: 

```
plot_totem <- function(SCE, plot.function, params = list(), plot.labels = TRUE, 
                       plot.polygons = TRUE, plot.trajectory = TRUE, 
                       plot.centroids = TRUE, plot.legend = FALSE) {
  # Packages required
  require("ggplot2")
  require("Totem")
  require("dynplot")
  
  # Plot 
  run.fun <- TRUE
  if (all( (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizSmoothedTraj)) & (plot.polygons == FALSE)) | 
      (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizMST)) & (plot.polygons == FALSE)) |
      (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizFeatureExpression)) & (plot.polygons == FALSE)))) run.fun <- FALSE
  if (run.fun) p <- do.call(plot.function, c(object = SCE, params))
  
  if (!plot.polygons) { # if 'plot.polygons' is FALSE, replace 'geom_polygon' by 'geom_point'
    if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizClustering)) | 
        isTRUE(all.equal(get(substitute(plot.function)), Totem::VizMST))) {
      if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizMST))) {
        vizmst.custom <- function (object, clustering.names = NULL, dim.red.type = NULL, viz.dim.red = NULL) {
          if (identical(reducedDimNames(object), character(0))) {
            message("No dimensionality reduced data available. ", 
                    "Using data in the 'logcounts' slot.")
            X <- logcounts(object)
            X <- as.matrix(Matrix::t(X))
          }
          else {
            X <- reducedDim(object)
          }
          if (!is.null(dim.red.type)) {
            X <- reducedDim(object, type = dim.red.type)
          }
          plot_list <- list()
          for (clustering_name in clustering.names) {
            clustering <- metadata(object)$totem$all.clustering[[clustering_name]]
            p <- Totem:::VizOneMST(viz.dim.red = viz.dim.red, X = X, clustering = clustering, 
                                   clustering.name = clustering_name)
            geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2), color = p$data$color)
            p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
            plot_list[[clustering_name]] <- p
          }
          p <- cowplot::plot_grid(plotlist = plot_list)
          return(p)
        }
        p <- vizmst.custom(object = SCE, clustering.names = params$clustering.names, params$dim.red.type, viz.dim.red = params$viz.dim.red)
      } else {
        if (plot.legend) {
          geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
          p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
        } else {
          geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2), color = p$data$color)
          p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
        }
      }
    } else if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizCellConnectivity))) {
      geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
      p$layers[[1]] <- geom.point$layers[[2]]
      p <- p + 
        scale_color_distiller("cell_connectivity expression", palette = "RdYlBu")
    } else if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizFeatureExpression))) {
      vizfeatureexpression.custom <- function (object, traj.name = NULL, feature.names = NULL, dim.red.type = NULL, 
                                               viz.dim.red = NULL, plot.traj = TRUE) {
        if (identical(reducedDimNames(object), character(0))) {
          message("No dimensionality reduced data available. ", 
                  "Using data in the 'logcounts' slot.")
          X <- logcounts(object)
          X <- as.matrix(Matrix::t(X))
        }
        else {
          X <- reducedDim(object)
        }
        if (!is.null(dim.red.type)) {
          X <- reducedDim(object, type = dim.red.type)
        }
        exp_matrix <- Matrix::t(logcounts(object))
        plot_list <- list()
        if (is.null(traj.name)) {
          clustering <- metadata(object)$totem$all.clustering[[1]]
          p_traj <- Totem:::VizOneMST(viz.dim.red = viz.dim.red, X = X, 
                                      clustering = clustering, clustering.name = "", return.traj = TRUE)
          model <- p_traj$traj
          for (feature_name in feature.names) {
            plot_list[[feature_name]] <- plot_dimred(model, dimred = viz.dim.red, 
                                                     feature_oi = feature_name, expression_source = exp_matrix, 
                                                     plot_trajectory = plot.traj)
            geom.point <- plot_list[[feature_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[feature_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
            plot_list[[feature_name]] <- plot_list[[feature_name]] + 
              scale_color_distiller(paste(feature_name, "expression"), palette = "RdYlBu")
          }
        }
        else {
          model <- metadata(object)$totem$dynwrap_trajectory[[traj.name]]
          for (feature_name in feature.names) {
            plot_list[[feature_name]] <- plot_dimred(model, dimred = viz.dim.red, 
                                                     feature_oi = feature_name, expression_source = exp_matrix, 
                                                     plot_trajectory = plot.traj) + ggtitle(traj.name)
            geom.point <- plot_list[[feature_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[feature_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
            plot_list[[feature_name]] <- plot_list[[feature_name]] + 
              scale_color_distiller(paste(feature_name, "expression"), palette = "RdYlBu")
          }
        }
        return(cowplot::plot_grid(plotlist = plot_list))
      }
      p <- vizfeatureexpression.custom(object = SCE, traj.name = params$traj.name, 
                                       feature.names = params$feature.names, 
                                       dim.red.type = params$dim.red.type, 
                                       viz.dim.red = params$viz.dim.red, 
                                       plot.traj = ifelse(is.null(params$plot.traj), TRUE, params$plot.traj))
    } else {
      vizsmoothedtraj.custom <- function (object, traj.names = NULL, 
                                          dim.red.type = NULL, 
                                          viz.dim.red = NULL, 
                                          plot.pseudotime = FALSE) {
        require("SingleCellExperiment")
        if (identical(reducedDimNames(object), character(0))) {
          message("No dimensionality reduced data available. ", 
                  "Using data in the 'logcounts' slot.")
          X <- logcounts(object)
          X <- as.matrix(Matrix::t(X))
        }
        else {
          X <- reducedDim(object)
        }
        if (!is.null(dim.red.type)) {
          X <- reducedDim(object, type = dim.red.type)
        }
        plot_list <- list()
        for (traj_name in traj.names) {
          model <- metadata(object)$totem$dynwrap_trajectory[[traj_name]]
          if (plot.pseudotime) {
            plot_list[[traj_name]] <- plot_dimred(model, color_cells = "pseudotime", 
                                                  dimred = viz.dim.red) + ggtitle(traj_name)
            geom.point <- plot_list[[traj_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[traj_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
            plot_list[[traj_name]] <- plot_list[[traj_name]] + ggplot2::scale_color_viridis_c("pseudotime")
          }
          else {
            plot_list[[traj_name]] <- plot_dimred(model, label_milestones = TRUE, 
                                                  dimred = viz.dim.red) + ggtitle(traj_name)
            geom.point <- plot_list[[traj_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[traj_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
          }
        }
        p <- cowplot::plot_grid(plotlist = plot_list)
        return(p)
      }
      p <- vizsmoothedtraj.custom(object = SCE, traj.names = params$traj.names,
                                  dim.red.type = params$dim.red.type, 
                                  viz.dim.red = params$viz.dim.red, 
                                  plot.pseudotime = ifelse(is.null(params$plot.pseudotime), FALSE, params$plot.pseudotime))
    }
  }
  
  # Remove layers
  eval.exp <- c(!plot.centroids, !plot.trajectory, !plot.labels)
  if (any(eval.exp)) {
    rm.layers <- c()
    if (!plot.centroids) rm.layers <- append(rm.layers, 2)
    if (!plot.trajectory) rm.layers <- append(rm.layers, 3:5)
    if (!plot.labels) rm.layers <- append(rm.layers, 6) 
    p$layers[rm.layers] <- NULL
  }
  
  # Add legend
  if (plot.legend) {
    # Keep the same colors
    cluster.names <- unique(p$data$milestone_id)
    color.names <- unique(p$data$color)
    # If you want a legend but keeping the same colors
    names(color.names) <- color.names
    names(cluster.names) <- color.names
    cluster.names <- cluster.names[order(nchar(cluster.names), cluster.names)]
    # Plot
    p <- p + scale_color_manual(name = "", values = color.names, labels = cluster.names, breaks = names(cluster.names)) +
      theme(legend.text = element_text(size=14, hjust=0.5), legend.title.position = "top") + 
      guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))
  }
  return(p)
}
```

See the examples below to run the `plot_totem()` function for the functions `VizMST()` and `VizFeatureExpression()`. 

Please adapt the variable names in order to match your variables, e.g., you might not have the `clustering.name` variable "17.358", but you can check trajectory/clustering names with the function `ReturnTrajNames(sce)`. The same applies to all the parameters. For instance you mentioned above that the function didn't work when you used `clustering = as.character(sce$cell_type)`, this is because you don't have this variable in your SingleCellExperiment metadata object. You can check the variables/data you've with `colData(sce)`.  

```
# Original
orig.vizmst.plt <- VizMST(sce, clustering.names = "17.358", viz.dim.red = dim_red)
orig.vizexp.plt <- VizFeatureExpression(sce, traj.name = "17.358", feature.names = "CD4", viz.dim.red = dim_red, plot.traj = TRUE)

# New
new.vizmst.plt <- plot_totem(SCE = sce, plot.function = VizMST, params = list(clustering.names = "17.358", viz.dim.red = dim_red), plot.polygons = FALSE)
new.vizexp.plt <- plot_totem(SCE = sce, plot.function = VizFeatureExpression, params = list(traj.name = "17.358", feature.names = "CD4", viz.dim.red = dim_red, plot.traj = TRUE), plot.polygons = FALSE)
``` 

Can you please run the function that didn't work above using the new `plot_totem()` version: 

```
plots <- plot_totem(SCE = sce, plot.function = VizSmoothedTraj, params = list(traj.names = ReturnTrajNames(sce), viz.dim.red = dim_red, plot.pseudotime = FALSE), plot.polygons = FALSE)
```

If this doesn't work again, please try the following: 

```
plots <- lapply(X =  ReturnTrajNames(sce), function(x) {
    plot_totem(SCE = sce, plot.function = VizSmoothedTraj, params = list(traj.names = x, viz.dim.red = dim_red, plot.pseudotime = FALSE), plot.polygons = FALSE)
})
plots <- cowplot::plot_grid(plotlist = plots)
plots
```

Please let us know below if this worked. 
Best regards, 
António

**Comment by wfujibuchilab** [comment]
Dear António,

I appreciate all your kind support on this issue.
The new plot_totem code excellently worked for all functions except for just one:
```r
traj <- "7.318"
plot <- plot_totem(SCE = sce, plot.function = VizSmoothedTraj, params = list(traj.names = traj, viz.dim.red = dim_red, plot.pseudotime = FALSE), plot.polygons = FALSE)
Coloring by milestone
Using milestone_percentages from trajectory
print(plot)
```
It does not matter either traj has single or multiple elements. This code outputs something funny graphic like:
![スクリーンショット 2024-09-27 14 09 57](https://github.com/user-attachments/assets/250be07c-97e9-4f8b-9d27-2ad566f8a9f2)
I hope that you understand the cause and could fix it soon. Thank you.

Best,
-WF

**Comment by antonioggsousa** [comment]
Dear Wataru, 

Thank you for your feedback. It's appreciated. 

Does the function works if you set `plot.pseudotime` `TRUE` instead of `FALSE`? 

Like this:

```
traj <- "7.318"
plot <- plot_totem(SCE = sce, plot.function = VizSmoothedTraj, params = list(traj.names = traj, viz.dim.red = dim_red, plot.pseudotime = TRUE), plot.polygons = FALSE)
Coloring by milestone
Using milestone_percentages from trajectory
print(plot)
```

Please let us know below. 

Best, 
António

**Comment by wfujibuchilab** [comment]
Hi,
Yes, it works and shows graphics if we set plot.pseudotime=TRUE. Thank you.
-WF

**Comment by antonioggsousa** [comment]
Hi, 

Thank you!

Please re-run the function with `plot.pseudotime=FALSE` with the new version of the `plot_totem()` function below: 

```
plot_totem <- function(SCE, plot.function, params = list(), plot.labels = TRUE, 
                       plot.polygons = TRUE, plot.trajectory = TRUE, 
                       plot.centroids = TRUE, plot.legend = FALSE) {
  # Packages required
  require("ggplot2")
  require("Totem")
  require("dynplot")
  
  # Plot 
  run.fun <- TRUE
  if (all( (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizSmoothedTraj)) & (plot.polygons == FALSE)) | 
      (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizMST)) & (plot.polygons == FALSE)) |
      (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizFeatureExpression)) & (plot.polygons == FALSE)))) run.fun <- FALSE
  if (run.fun) p <- do.call(plot.function, c(object = SCE, params))
  
  if (!plot.polygons) { # if 'plot.polygons' is FALSE, replace 'geom_polygon' by 'geom_point'
    if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizClustering)) | 
        isTRUE(all.equal(get(substitute(plot.function)), Totem::VizMST))) {
      if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizMST))) {
        vizmst.custom <- function (object, clustering.names = NULL, dim.red.type = NULL, viz.dim.red = NULL) {
          if (identical(reducedDimNames(object), character(0))) {
            message("No dimensionality reduced data available. ", 
                    "Using data in the 'logcounts' slot.")
            X <- logcounts(object)
            X <- as.matrix(Matrix::t(X))
          }
          else {
            X <- reducedDim(object)
          }
          if (!is.null(dim.red.type)) {
            X <- reducedDim(object, type = dim.red.type)
          }
          plot_list <- list()
          for (clustering_name in clustering.names) {
            clustering <- metadata(object)$totem$all.clustering[[clustering_name]]
            p <- Totem:::VizOneMST(viz.dim.red = viz.dim.red, X = X, clustering = clustering, 
                                   clustering.name = clustering_name)
            geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2), color = p$data$color)
            p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
            plot_list[[clustering_name]] <- p
          }
          p <- cowplot::plot_grid(plotlist = plot_list)
          return(p)
        }
        p <- vizmst.custom(object = SCE, clustering.names = params$clustering.names, params$dim.red.type, viz.dim.red = params$viz.dim.red)
      } else {
        if (plot.legend) {
          geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
          p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
        } else {
          geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2), color = p$data$color)
          p$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
        }
      }
    } else if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizCellConnectivity))) {
      geom.point <- p + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
      p$layers[[1]] <- geom.point$layers[[2]]
      p <- p + 
        scale_color_distiller("cell_connectivity expression", palette = "RdYlBu")
    } else if (isTRUE(all.equal(get(substitute(plot.function)), Totem::VizFeatureExpression))) {
      vizfeatureexpression.custom <- function (object, traj.name = NULL, feature.names = NULL, dim.red.type = NULL, 
                                               viz.dim.red = NULL, plot.traj = TRUE) {
        if (identical(reducedDimNames(object), character(0))) {
          message("No dimensionality reduced data available. ", 
                  "Using data in the 'logcounts' slot.")
          X <- logcounts(object)
          X <- as.matrix(Matrix::t(X))
        }
        else {
          X <- reducedDim(object)
        }
        if (!is.null(dim.red.type)) {
          X <- reducedDim(object, type = dim.red.type)
        }
        exp_matrix <- Matrix::t(logcounts(object))
        plot_list <- list()
        if (is.null(traj.name)) {
          clustering <- metadata(object)$totem$all.clustering[[1]]
          p_traj <- Totem:::VizOneMST(viz.dim.red = viz.dim.red, X = X, 
                                      clustering = clustering, clustering.name = "", return.traj = TRUE)
          model <- p_traj$traj
          for (feature_name in feature.names) {
            plot_list[[feature_name]] <- plot_dimred(model, dimred = viz.dim.red, 
                                                     feature_oi = feature_name, expression_source = exp_matrix, 
                                                     plot_trajectory = plot.traj)
            geom.point <- plot_list[[feature_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[feature_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
            plot_list[[feature_name]] <- plot_list[[feature_name]] + 
              scale_color_distiller(paste(feature_name, "expression"), palette = "RdYlBu")
          }
        }
        else {
          model <- metadata(object)$totem$dynwrap_trajectory[[traj.name]]
          for (feature_name in feature.names) {
            plot_list[[feature_name]] <- plot_dimred(model, dimred = viz.dim.red, 
                                                     feature_oi = feature_name, expression_source = exp_matrix, 
                                                     plot_trajectory = plot.traj) + ggtitle(traj.name)
            geom.point <- plot_list[[feature_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[feature_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
            plot_list[[feature_name]] <- plot_list[[feature_name]] + 
              scale_color_distiller(paste(feature_name, "expression"), palette = "RdYlBu")
          }
        }
        return(cowplot::plot_grid(plotlist = plot_list))
      }
      p <- vizfeatureexpression.custom(object = SCE, traj.name = params$traj.name, 
                                       feature.names = params$feature.names, 
                                       dim.red.type = params$dim.red.type, 
                                       viz.dim.red = params$viz.dim.red, 
                                       plot.traj = ifelse(is.null(params$plot.traj), TRUE, params$plot.traj))
    } else {
      vizsmoothedtraj.custom <- function (object, traj.names = NULL, 
                                          dim.red.type = NULL, 
                                          viz.dim.red = NULL, 
                                          plot.pseudotime = FALSE) {
        require("SingleCellExperiment")
        if (identical(reducedDimNames(object), character(0))) {
          message("No dimensionality reduced data available. ", 
                  "Using data in the 'logcounts' slot.")
          X <- logcounts(object)
          X <- as.matrix(Matrix::t(X))
        }
        else {
          X <- reducedDim(object)
        }
        if (!is.null(dim.red.type)) {
          X <- reducedDim(object, type = dim.red.type)
        }
        plot_list <- list()
        for (traj_name in traj.names) {
          model <- metadata(object)$totem$dynwrap_trajectory[[traj_name]]
          if (plot.pseudotime) {
            plot_list[[traj_name]] <- plot_dimred(model, color_cells = "pseudotime", 
                                                  dimred = viz.dim.red) + ggtitle(traj_name)
            geom.point <- plot_list[[traj_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
            plot_list[[traj_name]]$layers[[1]] <- geom.point$layers[[length(geom.point$layers)]]
            plot_list[[traj_name]] <- plot_list[[traj_name]] + ggplot2::scale_color_viridis_c("pseudotime")
          }
          else {
            plot_list[[traj_name]] <- plot_dimred(model, label_milestones = TRUE, 
                                                  dimred = viz.dim.red) + ggtitle(traj_name)
            if (plot.legend) {
              geom.point <- plot_list[[traj_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2, color = color))
              plot_list[[traj_name]]$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
            } else {
              geom.point <- plot_list[[traj_name]] + geom_point(mapping = aes(x = comp_1, y = comp_2), color = plot_list[[traj_name]]$data$color)
              plot_list[[traj_name]]$layers[[1]] <- geom.point$layers[[ length(geom.point$layers) ]]
            }
          }
        }
        p <- cowplot::plot_grid(plotlist = plot_list)
        return(p)
      }
      p <- vizsmoothedtraj.custom(object = SCE, traj.names = params$traj.names,
                                  dim.red.type = params$dim.red.type, 
                                  viz.dim.red = params$viz.dim.red, 
                                  plot.pseudotime = ifelse(is.null(params$plot.pseudotime), FALSE, params$plot.pseudotime))
    }
  }
  
  # Remove layers
  eval.exp <- c(!plot.centroids, !plot.trajectory, !plot.labels)
  if (any(eval.exp)) {
    rm.layers <- c()
    if (!plot.centroids) rm.layers <- append(rm.layers, 2)
    if (!plot.trajectory) rm.layers <- append(rm.layers, 3:5)
    if (!plot.labels) rm.layers <- append(rm.layers, 6) 
    p$layers[rm.layers] <- NULL
  }
  
  # Add legend
  if (plot.legend) {
    # Keep the same colors
    cluster.names <- unique(p$data$milestone_id)
    color.names <- unique(p$data$color)
    # If you want a legend but keeping the same colors
    names(color.names) <- color.names
    names(cluster.names) <- color.names
    cluster.names <- cluster.names[order(nchar(cluster.names), cluster.names)]
    # Plot
    p <- p + scale_color_manual(name = "", values = color.names, labels = cluster.names, breaks = names(cluster.names)) +
      theme(legend.text = element_text(size=14, hjust=0.5), legend.title.position = "top") + 
      guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))
  }
  return(p)
}
```

Please let us know if this time worked. 

Best, 
António

**Comment by wfujibuchilab** [comment]
Dear António,

Thanks for your quick update. It worked beautifully at least on my Intel MacPro this time.
<img width="797" alt="image" src="https://github.com/user-attachments/assets/4333130e-d4a2-4fa6-b76a-3dd3aa32354d">

Thank you so much for your dedicated support for this issue. We really appreciate it and hope it will be packaged in Totem soon.

Best regards,
-Wataru

**Comment by antonioggsousa** [comment]
Dear Wataru, 

Yes, we'll consider to add it in a new release. 

Best regards, 
António
